### ISSUE TITLE
Cannot start freshly-built image from docker compose

### ISSUE THREAD

**Issue by romansavrulin** [microsoft/BotFramework-Composer#1585]
## Describe the bug
After building a docker image composer service cannot start with 

```
Error: Cannot find module 'nanoid/generate'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/Composer/server/node_modules/@bfc/shared/lib/dialogFactory.js:55:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^
```

## Version
a4a2697

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu
- [x] Docker

## To Reproduce
docker-compose -up

## Expected behavior
Running system

**Comment by cwhitten** [comment]
hello @romansavrulin - this is a known issue and is fixed in our `master` branch. we anticipate updating the `stable` branch in the coming days, until then you can use the `master` branch when running Composer in a container, although the preferred method of running Composer is locally on your host machine.

**Comment by daltskin** [comment]
`docker-compose up` still failing for me on master branch with:
```bash
Step 16/26 : RUN yarn install
 ---> Running in 1b5aef354f40
yarn install v1.19.1
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@bfc%2feslint-plugin-bfcomposer: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/src/Composer/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'composer' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

**Comment by romansavrulin** [comment]
@daltskin try my master branch https://github.com/romansavrulin/BotFramework-Composer/tree/master

it also incorporates bot's WebUI + offline-directlie service to work locally.

remember to mount volume with BotProject dir on docker server, or botruntime won't allow you to create new bot

**Comment by cwhitten** [comment]
hey @daltskin - I've reproduced this and am taking a look. Thanks for your patience!
