### ISSUE TITLE
The source completed without providing data to receive

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/BotFramework-Composer#3321]
No matter what publish profile I'm using, I get this error:

> The source completed without providing data to receive

## Version

![image](https://user-images.githubusercontent.com/66222191/83750803-84a15380-a66e-11ea-96f2-2604900c6b90.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

## OS

- [x] Windows
- [ ] macOS
- [ ] Ubuntu

## To Reproduce

1. Generate publish config with the provisionComposer.js
2. Create a new profile
3. Paste the configuration, choose Publish bot to an Azure Web App (preview) and give a name
4. Click Save
5. (Click OK on this error message #3320)
6. Click "Publish to selected profile"

## Expected behavior

The publish will succeed.

## Screenshots

![image](https://user-images.githubusercontent.com/66222191/83750959-c16d4a80-a66e-11ea-91e4-84a8cd0bfed2.png)

**Comment by VanyLaw** [comment]
Hi @hraz-msft, can you check you log by clicking the log button to see which step went wrong?

**Comment by luhan2017** [comment]
@hraz-msft , could you start local and see whether it works. I suspect this is a dotnet build issue.
I searched and found similar issue here. could you double check you dotnet version and visual studio version? 
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/issues/43

**Comment by hraz-msft** [comment]
> Hi @hraz-msft, could you please check you log by clicking the log button to see which step went wrong?

Nothing interesting in the log...

![image](https://user-images.githubusercontent.com/66222191/83859610-d73e4680-a726-11ea-9f42-10a7e9094e17.png)

**Comment by hraz-msft** [comment]
> @hraz-msft , could you start local and see whether it works. I suspect this is a dotnet build issue.
> I searched and found similar issue here. could you double check you dotnet version and visual studio version?
> [damienbod/AspNet5IdentityServerAngularImplicitFlow#43](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/issues/43)

It my first time I'm using the Composer, so I not sure how to start local... 

My dotnet version: 3.1.201
My visual studio version: 16.6.1 (visual studio 2019)

What are the required versions for Composer?

**Comment by hraz-msft** [comment]
It seems that my access token is the root cause of the issue. I tried another access token (of my team member) and it was succeeded, but mine access token fails:

![image](https://user-images.githubusercontent.com/66222191/83970388-2a0e2e80-a8de-11ea-9497-51cc7f4f5569.png)

4:42p - My **personal** access token
4:38pm - My **team member** access token

Any idea why is that?? 

(I've created the resources in Azure with `provisionComposer.js` with my **personal** account)

**Comment by hraz-msft** [comment]
I have another update: I've tried to see the logs when I run composer locally, and I saw that Luis is the root source of the issue. When I provision the bot resources with `--createLuisResource false --createLuisAuthoringResource false` the publish succeeded.

<details>
  <summary>Click here to expand the logs (with Luis)</summary>

```
PUT /api/projects/14692.216011157378/files/appsettings.json 200 138.596 ms - 34
GET /api/publish/14692.216011157378/history/Publish 400 92.427 ms - 112
POST /api/publish/14692.216011157378/publish/Publish 202 179.911 ms - 170
PUT /api/projects/14692.216011157378/files/appsettings.json 200 99.910 ms - 34
{ status: 'DEPLOY_INFO', message: 'lubuild succeed' }
GET /api/publish/14692.216011157378/status/Publish 202 62.155 ms - 170
GET /api/publish/14692.216011157378/status/Publish 202 54.858 ms - 170
StatusCodeError: 400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  }\r\n}"
    at new StatusCodeError (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 400,
  error: '{\r\n' +
    '  "error": {\r\n' +
    '    "code": "BadArgument",\r\n' +
    '    "message": "The source completed without providing data to receive."\r\n' +
    '  }\r\n' +
    '}',
  options: {
    headers: {
      Authorization: 'Bearer XXXXXXXXXXXXXXXXXXXX',
      'Ocp-Apim-Subscription-Key': 'XXXXXXXXXXXXXXXXXXXX'
    },
    uri: 'https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts',
    method: 'GET',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'cache-control': 'no-store, proxy-revalidate, no-cache, max-age=0, private',
      pragma: 'no-cache',
      'content-length': '125',
      'content-type': 'application/json; charset=utf-8',
      'apim-request-id': '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'request-id': '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'request-context': 'appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      date: 'Mon, 08 Jun 2020 08:54:20 GMT',
      connection: 'close'
    },
    rawHeaders: [
      'Cache-Control',
      'no-store, proxy-revalidate, no-cache, max-age=0, private',
      'Pragma',
      'no-cache',
      'Content-Length',
      '125',
      'Content-Type',
      'application/json; charset=utf-8',
      'Apim-Request-Id',
      '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'Request-Id',
      '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'Strict-Transport-Security',
      'max-age=31536000; includeSubDomains; preload',
      'Request-Context',
      'appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b',
      'X-Content-Type-Options',
      'nosniff',
      'X-Frame-Options',
      'SAMEORIGIN',
      'Date',
      'Mon, 08 Jun 2020 08:54:20 GMT',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /luis/api/v2.0/azureaccounts HTTP/1.1\r\n' +
        'Authorization: Bearer XXXXXXXXXXXXXXXXXXXX \r\n' +
        'Ocp-Apim-Subscription-Key: XXXXXXXXXXXXXXXXXXXX \r\n' +
        'host: westus.api.cognitive.microsoft.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/luis/api/v2.0/azureaccounts',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      headers: [Object],
      uri: [Url],
      method: 'GET',
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function],
      _rp_reject: [Function],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function],
      _rp_options: [Object],
      setHeader: [Function],
      hasHeader: [Function],
      getHeader: [Function],
      removeHeader: [Function],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'westus.api.cognitive.microsoft.com',
      path: '/luis/api/v2.0/azureaccounts',
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts',
      req: [ClientRequest],
      ntick: true,
      response: [Circular],
      originalHost: 'westus.api.cognitive.microsoft.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '{\r\n' +
      '  "error": {\r\n' +
      '    "code": "BadArgument",\r\n' +
      '    "message": "The source completed without providing data to receive."\r\n' +
      '  }\r\n' +
      '}',
    [Symbol(kCapture)]: false
  }
}
StatusCodeError: 400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  }\r\n}"
    at new StatusCodeError (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (<ProjDir>\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 400,
  error: '{\r\n' +
    '  "error": {\r\n' +
    '    "code": "BadArgument",\r\n' +
    '    "message": "The source completed without providing data to receive."\r\n' +
    '  }\r\n' +
    '}',
  options: {
    headers: {
      Authorization: 'Bearer XXXXXXXXXXXXXXXXXXXX \r\n',
      'Ocp-Apim-Subscription-Key': XXXXXXXXXXXXXXXXXXXX'
    },
    uri: 'https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts',
    method: 'GET',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'cache-control': 'no-store, proxy-revalidate, no-cache, max-age=0, private',
      pragma: 'no-cache',
      'content-length': '125',
      'content-type': 'application/json; charset=utf-8',
      'apim-request-id': '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'request-id': '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'request-context': 'appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      date: 'Mon, 08 Jun 2020 08:54:20 GMT',
      connection: 'close'
    },
    rawHeaders: [
      'Cache-Control',
      'no-store, proxy-revalidate, no-cache, max-age=0, private',
      'Pragma',
      'no-cache',
      'Content-Length',
      '125',
      'Content-Type',
      'application/json; charset=utf-8',
      'Apim-Request-Id',
      '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'Request-Id',
      '575300c1-ffa7-48f1-9fe7-7361966db8d4',
      'Strict-Transport-Security',
      'max-age=31536000; includeSubDomains; preload',
      'Request-Context',
      'appId=cid-v1:26a3540d-a02a-4998-a060-715488fd769b',
      'X-Content-Type-Options',
      'nosniff',
      'X-Frame-Options',
      'SAMEORIGIN',
      'Date',
      'Mon, 08 Jun 2020 08:54:20 GMT',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: 'westus.api.cognitive.microsoft.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'westus.api.cognitive.microsoft.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(asyncId)]: 112624,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /luis/api/v2.0/azureaccounts HTTP/1.1\r\n' +
        'Authorization: Bearer XXXXXXXXXXXXXXXXXXXX \r\n' +
        'Ocp-Apim-Subscription-Key: XXXXXXXXXXXXXXXXXXXX \r\n' +
        'host: westus.api.cognitive.microsoft.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/luis/api/v2.0/azureaccounts',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      headers: [Object],
      uri: [Url],
      method: 'GET',
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function],
      _rp_reject: [Function],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function],
      _rp_options: [Object],
      setHeader: [Function],
      hasHeader: [Function],
      getHeader: [Function],
      removeHeader: [Function],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'westus.api.cognitive.microsoft.com',
      path: '/luis/api/v2.0/azureaccounts',
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts',
      req: [ClientRequest],
      ntick: true,
      response: [Circular],
      originalHost: 'westus.api.cognitive.microsoft.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '{\r\n' +
      '  "error": {\r\n' +
      '    "code": "BadArgument",\r\n' +
      '    "message": "The source completed without providing data to receive."\r\n' +
      '  }\r\n' +
      '}',
    [Symbol(kCapture)]: false
  }
}
GET /api/publish/14692.216011157378/status/Publish 500 72.391 ms - 592
```
</details>

**Comment by luhan2017** [comment]
@hraz-msft  Did you create both luis authoring and prediction resources in the provision process? Do you mind to sync up with me on Team about this issue?

**Comment by hraz-msft** [comment]
@luhan2017 This issue was solved by Luis team. Apparently, my account had some incorrect settings and 'hen I called the API I would get an error due to my issues in my account. 

Luis team fixed my account and now it seems to be working, so I will close that issue. Thanks you!

**Comment by zidaneymar** [comment]
Not sure about the reason.
Based on the log, the request to https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts
failed. This API is used for retrieving user's luis account using access token and luis authoring key.
If the authoring key is not created by the token owner, the api would return 
```
{
    "statusCode": 401,
    "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired."
}
```
It seems that the token is invalid for some reason.

**Comment by engineererr** [comment]
@hraz-msft I experience the same issue still. What exactly did you ask the LUIS team to do? Thank you

Publish log:

`Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\interuption\\cancel.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\interuption\\help.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\interuption\\purpose-bot.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\interuption\\PurposeDialog.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\cancel.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\help.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\purpose-bot.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\dummy\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\dad5cd9069c251df3c8020a205dd0921\\azurewebapp\\ComposerDialogs\\generated\\PurposeDialog.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\",\"error\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadArgument\\\",\\r\\n    \\\"message\\\": \\\"The source completed without providing data to receive.\\\"\\r\\n  }\\r\\n}\",\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\n    at new StatusCodeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\errors.js:32:15)\\n    at Request.plumbing.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:46:31)\\n    at Request.self.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:185:22)\\n    at Request.emit (events.js:210:5)\\n    at Request.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1154:10)\\n    at Request.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1076:12)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  }\r\n}"`
