### ISSUE TITLE
Publishing a BOT fails with a ENOENT: no such file or directory open

### ISSUE THREAD

**Issue by cevans-or** [microsoft/BotFramework-Composer#3452]
## Describe the bug
I am trying to publish a BOT to the Azure portal using the BOT composer.  I run
the  node provisionComposer.js command to create Azure resources and the publish
profile.  The AZ resources are successfully created in the portal and the publish configuration
is created.  I then create a new publish profile within Composer and then add the newly created publish configuration  to the Publish configuration section of the new profile.

When I tried to publish the profile I get the following error:
ENOENT: no such file or directory, open '/home/xxxxx/bot-composer-dev/BotFramework-Composer-1.0.0/Composer/plugins/azurePublish/lib/publishBots/5b4b1f8a8df2148c1e17919fd157cb79/azurewebapp/appsettings.deployment.json'

## Version
4.9.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [x ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x ] Ubuntu

## To Reproduce

See above

## Expected behavior

The BOT is successful in publishing to the Azure portal

**Comment by hibrenda** [comment]
@zidaneymar

**Comment by zidaneymar** [comment]
I can repro this issue. It's a weird behavior, after creating a new publishing profile and clicking publish, the azure deploy page would pop up a failure message at first and come up with a success deployment, @VanyLaw could you help figure out the reason? I think we should check the copy process is ready before deploying.
![image](https://user-images.githubusercontent.com/9328933/85382382-7bbae800-b571-11ea-9c3d-565f719e2886.png)

**Comment by zidaneymar** [comment]
@hibrenda  I have verified that this issue happens occasionally, not sure about the reason.

**Comment by VanyLaw** [comment]
Can not reproduce. But Maybe it's the issue during folder zipping, which we fixed in #3557 .

**Comment by zidaneymar** [comment]
Close this since can't repro anymore.

**Comment by reinoldus** [comment]
Hi, I am still having this issue. I am running v1.0.2 on ubuntu 20.04.

The directory: "/home/ubuntu/BotFrameworkComposer/publishBots/" is empty.

Exact error is:

```
[Error: ENOENT: no such file or directory, open '/home/ubuntu/BotFrameworkComposer/publishBots/xxx/azurefunctions/appsettings.deployment.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ubuntu/BotFrameworkComposer/publishBots/xxx/azurefunctions/appsettings.deployment.json'
}

```
