### ISSUE TITLE
Issue Publishing Composer Bot to Azure Web App Bot

### ISSUE THREAD

**Issue by Trubzzz** [microsoft/BotFramework-Composer#3722]
I've created a bot locally through the Composer Desktop Application (v1.0.2) using Luis for intent and entity recognition. I'm able to test the bot through the emulator with no issues, so naturally I'm trying to publish the bot to our Azure Portal so other users may test it.

The issue I'm running into is I cannot get the bot published following this documentation:
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

I've tried creating a brand new resource group through the command line, followed up by pasting the resulting JSON into a publish profile in Composer (with a success message), but when I select 'Test in Web Chat', the bot does not present the welcome message nor handle any inputs I give it. I've also tried creating a Web App Bot using a smaller JSON file to create a second publishing profile in Composer (also with a success message) with the exact same result, no greeting and inputs not being handled.

I'm not sure what my next troubleshooting step should be, so any input would be greatly appreciated.

**Comment by zxyanliu** [comment]
@Trubzzz thanks for reporting your issue. 
Can you share your JSON file for publishing so that we can troubleshoot for you?

**Comment by Trubzzz** [comment]
Sure thing. If you need the specifics, I don't mind providing those as well. Just wanted to get a baseline first to ensure I'm using the correct information to begin with, 

{
"accessToken": "<access token provided from 'az account get-access-token'>",
"hostname": "<name of web app bot>",
"luisResource": "<name of Cognitive Services in Azure portal (also name of Authoring Resource in Luis.ai)>", 
"settings": {
    "luis": {
    "endpointKey": "<endpoint key used when publishing/restart bot in Composer>",
    "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
    "authoringKey": "",
    "region": "westus"
        },
    "MicrosoftAppId": "<found in Configuration Application Settings in Azure Portal>",
    "MicrosoftAppPassword": "<found in Configuration Application Settings in Azure Portal>"
    }
}

**Comment by zxyanliu** [comment]
Hi @Trubzzz I tested a ToDoWithLUIS sample bot today. I was unable to reproduce the error you had. 
I felt it easier to start by [creating all the new Azure resources](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources), and then copy the generated JSON file from the command line and [paste it to your Composer publish configuration](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-new-azure-resources).  

I am wondering if you would like to try again? 

![image](https://user-images.githubusercontent.com/32497439/88757667-71b17980-d11b-11ea-99fa-09736930b9d3.png)

**Comment by eluchsinger** [comment]
I can reproduce the error. I've created a bot and everything works in the emulator. When I run the provisionComposer and it creates all the new Azure resources, the Test In Web Chat does not work and is just empty.

I think the endpoint for the bot is actually not available (is it hosted in the WebApp?)

**Comment by eluchsinger** [comment]
@zxyanliu 

Actually, you seem to have a Web App Bot and I have a `Bot Channels Registration`.

And I've got the following message after copying the generated JSON into the composer.

![image](https://user-images.githubusercontent.com/12324017/88810501-b5f15800-d1b5-11ea-878c-6992beafb0a6.png)

Even if the publisher says the publishing was successful:

![image](https://user-images.githubusercontent.com/12324017/88810645-ed600480-d1b5-11ea-9691-ae84a765e69b.png)

**Comment by zxyanliu** [comment]
@eluchsinger this error message is a known issue. You can just click **OK** and proceed. Did you get your bot published with success? 
@hibrenda can we get someone to fix the error message?

**Comment by eluchsinger** [comment]
@zxyanliu I removed the newly created resource group, generated all resources again and published manually again. The same error happened. After I published manually a second time, it started working properly.

I believe there was an issue with the earlier deployments and they actually failed, even if the message was "success".

**Comment by zxyanliu** [comment]
@eluchsinger thanks for the update.

**Comment by Trubzzz** [comment]
Hi @zxyanliu, 

Thanks for the replies, but I'm still unable to publish after creating a brand new resource group. I've tried both creating a brand new resource group altogether per the documentation provided above as well as publishing to a Web App Bot that already exists in my portal. 

Is there any additional troubleshooting step I can take? I can run my bot in the Bot Composer Desktop Application and I get successes on both Composer publish profiles (the new resource group profile and the existing Web App Bot profile), but each **Test in Web Chat** conversation sits idle without presenting the welcome message or responding to any kind of text input.

Also, thanks @eluchsinger for looking into this as well.

**Comment by reinoldus** [comment]
I am having the same issue.
I also raised this support request, but the suggested fixes didn't work: https://docs.microsoft.com/en-us/answers/questions/72356/deployment-to-azure-fails.html

Additionally I am affected by this bug #3452 so I have to do everything using the latest branch from the git repo.

`node provisionComposer.js --subscriptionId=XXXX  --tenantId=XXX --name=XXXX --appPassword=XXX --environment=dev`

I had to put the tenantId because of some other bug.

I also tried to deploy it via functions -> no success
I tried my own bot, I tried sample doesn't work

Help would be very much appreciated

**Comment by reinoldus** [comment]
I just spun up a Windows-VM and tried to deploy again and it works using windows. I hope that helps to debug the issue.

Here are the details of my ubuntu machine, if it helps:

```
ubuntu@ubuntu-ThinkPad-P43s:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
ubuntu@ubuntu-ThinkPad-P43s:~$ node --version
v12.18.3
ubuntu@ubuntu-ThinkPad-P43s:~$ uname -a
Linux ubuntu-ThinkPad-P43s 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu-ThinkPad-P43s:~$ 
```

**Comment by saikumaru** [comment]
I still get the same errors when published to Azure functions
I also see this error which I am unable to resolve

![image](https://user-images.githubusercontent.com/44021002/94008255-56cc5000-fdc0-11ea-8732-ca3b9f1c1844.png)

**Comment by jh70zape** [comment]
I get exactly the same issue. Tried to publish from Composer and it said success. Got back to the azure Web App Bot, showing nothing in the test chat (supposed to give greetings). Do you guys have any new update on fixing it?

**Comment by jwiley84** [comment]
Assigning to @v-kydela as I'm unable to run composer at the moment.

**Comment by v-kydela** [comment]
@Trubzzz - I was able to reproduce your problem at first, but when I went to the channels blade and then back to the Test in Web Chat blade the bot began responding immediately. Perhaps the app service just needs a moment to start up. Does your bot work after leaving and coming back?

**Comment by v-kydela** [comment]
@Trubzzz - Are you still working on this?

**Comment by jh70zape** [comment]
@v-kydela I am still struggling with that without further progress.

**Comment by v-kydela** [comment]
@jh70zape - Have you tried any of the advice in this thread? I am not able to help you without more information. Please provide the following:

1. Links
1. Repro steps
1. Screenshots

**Comment by tekram** [comment]
> @zxyanliu I removed the newly created resource group, generated all resources again and published manually again. The same error happened. After I published manually a second time, it started working properly.
> 
> I believe there was an issue with the earlier deployments and they actually failed, even if the message was "success".

@eluchsinger Can you clarify what you did to solve this? I am running into the same error. How did you publish it manually?

**Comment by luhan2017** [comment]
@Trubzzz This seems like the same issue with #4348, could you please check on this? We have a PR on this already, will let you know when it get merged.

**Comment by v-kydela** [comment]
I will close this issue because the PR has already been merged. The deployment process for Composer is still being worked on, and if your bot is slow to respond after deployment then that may have nothing to do with Composer anyway. For anyone else having difficulty with their bot responding slowly after being deployed, please refer to the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0#my-bot-is-slow-to-respond-to-the-first-message-it-receives-how-can-i-make-it-faster) for troubleshooting info.

**Comment by normthecat** [comment]
The number of keys, configurations, services, blah blah blah is ridiculous. Why do you think Dialogflow and Google are the standards? They work. This is garbage.
