### ISSUE TITLE
Prebuilt Entity datetimeV2 extraction: Can't get Resolution

### ISSUE THREAD

**Issue by anemit** [microsoft/BotFramework-Composer#5389]
I am trying to extract entities out of order, geographyV2 and datetimeV2 specifically. I extract geographyV2 successfully but as far as datetimeV2 is concerned I cant get the raw response to use the resolution value. I can only get RecognizerResult (datetime) in which resolution is not included. 
Also I have set includeAPIResult to true after I searched for similar issues.
The same problem exists when "Ask for user input" is used to extract both geographyV2 and datetimeV2 entities.
![Screenshot_1](https://user-images.githubusercontent.com/48094685/102604111-60015a80-412c-11eb-9508-837be1d16733.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/48094685/102604118-61328780-412c-11eb-96b8-4ea6de20388f.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/48094685/102604120-61cb1e00-412c-11eb-9a6a-1122c4652667.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/48094685/102604125-6263b480-412c-11eb-8972-2091025f3c2b.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/48094685/102604126-62fc4b00-412c-11eb-8557-bc118ac26dea.jpg)

**Comment by dmvtech** [comment]
I am investigating this.

**Comment by dmvtech** [comment]
HI @anemit

I was able to reproduce the issue, still not sure what the resolution or cause is yet. I did notice that you were using the same term for some labels as well as roles (specifically `te`). Do both of your prebuilt entities need to have roles?

**Comment by feich-ms** [comment]
Hi @dmvtech @anemit currently the resolution is not extracted into the standard recognizer result, but you can have a workaround solution to get it. Just set the includeAPIResult to true in your recognize file(naming `{YourBotName}.en-us.lu.dialog}`) of your bot like bwlow:

![image](https://user-images.githubusercontent.com/43032123/103984943-ffad8800-51c2-11eb-95e3-f513a77e822b.png)


And then consume the recognizer result like below. Use `turn.recognized.luisResult.prediction.entities`
![image](https://user-images.githubusercontent.com/43032123/103984996-1a7ffc80-51c3-11eb-81cf-74d12ac9f677.png)

You will see the resolution is extracted as below:
![image](https://user-images.githubusercontent.com/43032123/103985123-5a46e400-51c3-11eb-9ad3-a7a01a3e7ea4.png)

Please let me know if you run into any issues

**Comment by anemit** [comment]
> HI @anemit
> 
> I was able to reproduce the issue, still not sure what the resolution or cause is yet. I did notice that you were using the same term for some labels as well as roles (specifically `te`). Do both of your prebuilt entities need to have roles?

Thank you for your time. When I don't use a role for prebuilt entities, the composer sends syntax error in Trigger Phrases.

**Comment by anemit** [comment]
> Hi @dmvtech @anemit currently the resolution is not extracted into the standard recognizer result, but you can have a workaround solution to get it. Just set the includeAPIResult to true in your recognize file(naming `{YourBotName}.en-us.lu.dialog}`) of your bot like bwlow:
> 
> ![image](https://user-images.githubusercontent.com/43032123/103984943-ffad8800-51c2-11eb-95e3-f513a77e822b.png)
> 
> And then consume the recognizer result like below. Use `turn.recognized.luisResult.prediction.entities`
> ![image](https://user-images.githubusercontent.com/43032123/103984996-1a7ffc80-51c3-11eb-81cf-74d12ac9f677.png)
> 
> You will see the resolution is extracted as below:
> ![image](https://user-images.githubusercontent.com/43032123/103985123-5a46e400-51c3-11eb-9ad3-a7a01a3e7ea4.png)
> 
> Please let me know if you run into any issues

Thank you. I have implemented your solution and it works fine.

**Comment by anemit** [comment]
I am closing this issue as the solution is presented in @feich-ms 's comment

**Comment by psingla321** [comment]
> turn.recognized.luisResult

Hi, I tried with your solution. But still not able to get raw response data. Its just providing recognizer result, in which resolution object not exist
