### ISSUE TITLE
Not able to change the Recognizer Type

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#5426]
## Describe the bug

Not able to change the Recognizer Type 

## Version

1.3.0

## Desktop

Desktop application

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Ref the attached video.

## Expected behavior

Recognizer Type should be change.

## Screenshots

Ref the attached video.

## Additional context

https://user-images.githubusercontent.com/16264167/103413792-44aa3c80-4b7b-11eb-9356-b0706e3bc1b0.mp4

**Comment by dmvtech** [comment]
I am able to reproduce this, but only when selecting the Bot _project_, not the _dialog_. @rvinothrajendran Can you confirm the same? 

![image](https://user-images.githubusercontent.com/43397658/103419927-f761a700-4b49-11eb-9600-53edb692cd6b.png)

**Comment by rvinothrajendran** [comment]
@dmvtech yes you are right

**Comment by dmvtech** [comment]
Thank you. Also found out odd behavior:

1. Change recognizer type while bot project is selected
2. Go to dialog and change a different property (`auto end dialog` for example)
3. That will refresh the recognizer type in the dialog (and project if you go back and select that).

So, when changing the recognizer when project is selected actually does change it. It just doesn't get reflected.

**Comment by zhixzhan** [comment]
Now when select "bot project" header, will auto navigate to it's main dialog, then change the Recognizer Type will be doable.
addressed in #5623

**Comment by v-kydela** [comment]
It looks like #5623 should be in 1.3.1, but the problem is still reproducing in 1.3.1
