### ISSUE TITLE
Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by tiagonmas** [microsoft/BotFramework-Composer#5697]
## Describe the bug

Started having the following issues running my bot, after the Greeting dialog I get the answer "Response status code does not indicate success: 404 (Not Found)."

```
{
  "type": "message",
  "serviceUrl": "http://localhost:65272",
  "channelId": "emulator",
  "from": {
    "id": "e92f1780-670f-11eb-bac1-89ebb61af8ed",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "e9324bd0-670f-11eb-b012-3d1aa5ef5145|livechat"
  },
  "recipient": {
    "id": "cb96af04-1a25-4896-947f-83e111d51d9b",
    "role": "user"
  },
  "locale": "en-US",
  "text": "Response status code does not indicate success: 404 (Not Found).",
  "inputHint": "acceptingInput",
  "replyToId": "199a1c80-6710-11eb-b012-3d1aa5ef5145",
  "id": "1a00a680-6710-11eb-b012-3d1aa5ef5145",
  "localTimestamp": "2021-02-04T17:40:41+00:00",
  "timestamp": "2021-02-04T17:40:41.832Z"
}
```

I'm guessing this is related to LUIS configuration .. but could not yet found how.

## Version

v1.3.1- nightly-209116.285a040

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
@tiagonmas This may relate to #5622. But that should be fixed in the latest nightly. Could you give me information here? What does your bot looks like? Are you using a custom runtime?

**Comment by tiagonmas** [comment]
Thanks @luhan2017. I am using a custom runtime, yes. Will check the other issue.

**Comment by tiagonmas** [comment]
I checked the other issue, and uninstalled the nightly builds and installed the production build of composer (v.1.3.0) but still see the issue. I fired F12 and fiddler, but I could not see the LUIS call as shown on the other issue ...

**Comment by tiagonmas** [comment]
LUIS  App was not published for some reason. Going to luis.ai and publishing the  app solved the issue.

**Comment by lauren-mills** [comment]
Can confirm. On latest nightlies and my LUIS apps were not being published

**Comment by luhan2017** [comment]
@lauren-mills and @tiagonmas, in the latest composer, we update the luis publishing from slot publish to version publish. if you bot works well when you manually publish the app, it is possible that, in composer it publishes luis by version, but your didn't update the code in the runtime side. Could you please check your runtime package version? is it later than 4.12.0-daily.20201202?

**Comment by tiagonmas** [comment]
@luhan2017 can you please clarify what package you are talking about ?
Here are my packages inside the webapp
![image](https://user-images.githubusercontent.com/42462/107160313-6920e200-698d-11eb-8c39-8eea003c7228.png)

**Comment by luhan2017** [comment]
@tiagonmas Yes, the 4.11.0 are the sdk packages you are using, if you want to use the latest nightly composer, you will need to upgrade those packages to 4.12 daily like this:

https://github.com/microsoft/BotFramework-Composer/blob/30d3ec2e4e6b75b7d68e726dcfb53d62520f0b70/runtime/dotnet/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj#L19

**Comment by tiagonmas** [comment]
Updated the project to 4.12.0-daily.* but still getting the same 404 errors when runnint the bot :(

![image](https://user-images.githubusercontent.com/42462/107235946-1ee74180-6a1d-11eb-9959-068ce27457ab.png)

**Comment by goergenj** [comment]
Hi, I just installed the nightly and also have the same issue. The Bot does not publish the LUIS app. Manually publishing the LUIS Apps solves the 404 but is not feasible,

**Comment by mramirezsal** [comment]
im having the same problem, but with v1.3.1
only works with 1.3.1-nightly.212216.8cde5d7
could be the same issue?

**Comment by luhan2017** [comment]
Yes, should be the same issue.  #5749, here is the PR to fix the issue, stay tuned.

**Comment by luhan2017** [comment]
This should be fixed in the 1.4
