### ISSUE TITLE
Form generation is broken because composer copies root LG templates to children LG files

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#5763]
## Describe the bug

If you build a form and generate it, you will get a whole lot of errors.  The reason seems to be that composer is copying root bot templates into the child LG files as empty templates which then causes there to be duplicate template names.

Everything after > Generator was added by composer--it should not.

```
[Name](Name/sandwich-Name.en-us.lg)
[personNameEntity](form/sandwich-personNameEntity.en-us.lg)
[Bread](Bread/sandwich-Bread.en-us.lg)
[BreadEntity](Bread/sandwich-BreadEntity.en-us.lg)
[Meat](Meat/sandwich-Meat.en-us.lg)
[MeatEntity](Meat/sandwich-MeatEntity.en-us.lg)
[Cheese](Cheese/sandwich-Cheese.en-us.lg)
[CheeseEntity](Cheese/sandwich-CheeseEntity.en-us.lg)
[Toppings](Toppings/sandwich-Toppings.en-us.lg)
[ToppingsEntity](Toppings/sandwich-ToppingsEntity.en-us.lg)
[Sauces](Sauces/sandwich-Sauces.en-us.lg)
[SaucesEntity](Sauces/sandwich-SaucesEntity.en-us.lg)
[moneyEntity](form/sandwich-moneyEntity.en-us.lg)
[Price](Price/sandwich-Price.en-us.lg)
[Quantity](Quantity/sandwich-Quantity.en-us.lg)
[numberEntity](form/sandwich-numberEntity.en-us.lg)
[dimensionEntity](form/sandwich-dimensionEntity.en-us.lg)
[Length](Length/sandwich-Length.en-us.lg)
[booleanEntity](form/sandwich-booleanEntity.en-us.lg)
[stringEntity](form/sandwich-stringEntity.en-us.lg)
[form-Choose](form/sandwich-form-Choose.en-us.lg)
[form-DisplayOperation](form/sandwich-form-DisplayOperation.en-us.lg)
[form-Show](form/sandwich-form-Show.en-us.lg)
[form](form/sandwich-form.en-us.lg)

> Generator: 5094d744401f1289098a7a1995f9bb91
# Name_Help()
-
# Name_ClearConfirmation()
-
# Name_Show()
-
LOTS MORE
```

## Version
![image](https://user-images.githubusercontent.com/17637681/107676523-175aaf00-6c4e-11eb-975f-853383f90221.png)

## Browser

- [ x] Electron distribution

## OS

- [x ] Windows

**Comment by cwhitten** [comment]
Confirming this was introduced with https://github.com/microsoft/BotFramework-Composer/pull/5654/files#diff-162b91f4bfa5ad1bb490a2801ddf6501ef4cf3670788845862ec2c2c8a1b8e4fR29

**Comment by boydc2014** [comment]
@zhixzhan  can you check this one? seems like when trying to aligning lg templates for multiple languages, we are over-copying lg templates here

**Comment by zhixzhan** [comment]
@boydc2014 fixed by expanding search to all imported files, in #5823

**Comment by chrimc62** [comment]
This still happens if you create two forms.  To repro:
1) Create a form 'foo' and hit generate.
2) Create a second form 'blah' and hit generate.
You will get two errors where the bot LG definitions are copied into both form root LG files.
![image](https://user-images.githubusercontent.com/17637681/109368537-4bd58a00-784e-11eb-8925-ff5132a38287.png)

**Comment by cosmicshuai** [comment]
verified
