### ISSUE TITLE
No error shows multiple error in Diagnostics - not able to Start Bot

### ISSUE THREAD

**Issue by anmolgandhi007** [microsoft/BotFramework-Composer#6196]
Hi,

I am getting two errors for 7 times in a row (even if its an error, why its getting duplicated 6 other times?). Another surprising element is there is no actual error and also the LG file shows no error.
Because of this strange behavior of errors coming up without being an actual one I am not able to Start my bot.

Please find below the Diagnostics page view:
![image](https://user-images.githubusercontent.com/25576582/109964254-73779700-7d13-11eb-96e7-48c6df35c1b4.png)
![image](https://user-images.githubusercontent.com/25576582/109964563-d832f180-7d13-11eb-83ff-4f0d7f5f9d62.png)

Attached LG files:
![Screenshot 2021-03-04 180833](https://user-images.githubusercontent.com/25576582/109965403-ef261380-7d14-11eb-9873-1c15d94ddaa9.png)
![Screenshot 2021-03-04 180714](https://user-images.githubusercontent.com/25576582/109965455-01a04d00-7d15-11eb-8528-b3399ca19a88.png)

PS- This is my first time posting any issue. I hope I was clear. Let me know if more clarification required. Thanks.

**Comment by boydc2014** [comment]
@lei9444  can you help take a look at this one

**Comment by boydc2014** [comment]
@anmolgandhi007  Thanks for trying and reporting, can you help attach the lg file?

**Comment by anmolgandhi007** [comment]
Please find attached LG file for your reference:

[lgfile.txt](https://github.com/microsoft/BotFramework-Composer/files/6084014/lgfile.txt)

**Comment by lei9444** [comment]
Hi @anmolgandhi007 which composer's version did you use? I am looking into this issue. I can't reproduce it in main branch now, did you use electron app or web app?

**Comment by anmolgandhi007** [comment]
Hi @lei9444, I am using desktop application of Bot framework composer(v 1.3.1).
Actually I am not using a newline in those function parameters, it moved itself in the newline as per the space provided for data in a single line.

**Comment by lei9444** [comment]
> Hi @lei9444, I am using desktop application of Bot framework composer(v 1.3.1).
> Actually I am not using a newline in those function parameters, it moved itself in the newline as per the space provided for data in a single line.

Hi, @anmolgandhi007 , could you help to remove the space and line break to see if the error will disappear? And could you reproduce the issue 'it moved itself in the newline as per the space provided for data in a single line'? I can't reproduce it. If you can help to put a gif or screen video about it here, it will be more helpful to find the root cause.

**Comment by anmolgandhi007** [comment]
https://user-images.githubusercontent.com/25576582/110906531-12168000-8332-11eb-8789-b6d297c71d6d.mp4

Here is the video you requested.

**Comment by anmolgandhi007** [comment]
Update: - Issues were found in the other language lg files.(de-de, es-es etc.) and there were other 7 language files other than en-us under dialogs-> *dialog name* -> language generation folder and all of them were having the same issue, hence the reason of same issue replicating 7 times. I have no clue how other language file got updated when I am working in en-us version of bot. I corrected the malformed other language lg files in an editor and again opened the bot in the Composer and the issues no more exist.

Before correction- 
Refer to line number 3 in below SS-
![image](https://user-images.githubusercontent.com/25576582/110915041-30ce4400-833d-11eb-9062-a6b83d247092.png)
Refer to line number 5 in below SS-
![image](https://user-images.githubusercontent.com/25576582/110915132-4479aa80-833d-11eb-892c-f04909467e08.png)

After correction- 
![image](https://user-images.githubusercontent.com/25576582/110915963-4bed8380-833e-11eb-8ca4-b09cabcecc8c.png)
![image](https://user-images.githubusercontent.com/25576582/110916022-5c056300-833e-11eb-98cc-d62c082b251b.png)

I don't know how it came in the first place. Let me know if you need more details. Happy to help.

**Comment by carlosscastro** [comment]
Thanks for the update! Closing since this is fixed

**Comment by anmolgandhi007** [comment]
Hey @carlosscastro, issue is still unidentified w.r.t. Bot framework composer. More people in the future can face this issue. Can it still be marked as "closed"?
