### ISSUE TITLE
Can't validate input when length is > 500

### ISSUE THREAD

**Issue by ysnoek2** [microsoft/BotFramework-Composer#8071]
## Describe the bug

I realized that a user can't make an input of more than 500 characters without getting an error. I want to validate the input before so the user doesn't get an error but a friendly message but it doesnt seem to work.

this is the error:
![image](https://user-images.githubusercontent.com/76207835/121879969-bd5a1b00-cd0d-11eb-8175-9971d5ce10ce.png)

this is the validation rule:
![image](https://user-images.githubusercontent.com/76207835/121880033-d2cf4500-cd0d-11eb-9eea-f084254f7992.png)

It gives the same error in Teams as in the emulator

## Version
V1.3.0
## OS

- [ ] macOS
- Windows
- [ ] Ubuntu

## Expected behavior

I would like for the bot composer to validate the input and give a friendly response when the input is larger than 500 characters

**Comment by dmvtech** [comment]
Hi @ysnoek2 Can you make sure that you are selecting write an expression? When doing so, it should prompt to put an equal sign `=` at the beginning. You should then have:

`=length(string(this.value)) <= 500`

For clarity; I am running v2.0.0 version of Composer. Here's what the dialog snippet looks like:
```json
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "65j1eJ"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "prompt": "${TextInput_Prompt_65j1eJ()}",
          "unrecognizedPrompt": "",
          "invalidPrompt": "${TextInput_InvalidPrompt_65j1eJ()}",
          "property": "user.largetext",
          "validations": [
            "=length(string(this.value)) <= 500"
          ]
        },
```

**Comment by dmvtech** [comment]
@ysnoek2 I'm going to assume this is resolved as it works for me with the above expression. If not; please comment and let us know if it behaved any differently.

**Comment by ysnoek2** [comment]
@dmvtech sorry for the late reply! I tried it but still get the same errormessage:
![image](https://user-images.githubusercontent.com/76207835/123068553-48c06400-d412-11eb-92c8-a48f23614753.png)
![image](https://user-images.githubusercontent.com/76207835/123068633-5970da00-d412-11eb-8046-f2705743b4cd.png)

**Comment by ysnoek2** [comment]
And i updated to 2.0.0 btw but still the same

**Comment by dmvtech** [comment]
@ysnoek2 Do you see any error traces when reproducing in Emulator? Can you please share that if so?

**Comment by ysnoek2** [comment]
@dmvtech I only see the messages i provided above

**Comment by dmvtech** [comment]
@ysnoek2 Are you able to share your bot to see if I can reproduce the issue with it?

**Comment by ysnoek2** [comment]
@dmvtech Yes, i gave you access to the repository

**Comment by dmvtech** [comment]
Thank you. I was able to confirm this is a known bug and being tracked here:
https://github.com/microsoft/botbuilder-dotnet/issues/5757

I am closing this as the issue is identified. Please keep an eye out on the bug linked for resolution.
