### ISSUE TITLE
Azure sign in fails when behind proxy

### ISSUE THREAD

**Issue by JohnRobertGreen** [microsoft/BotFramework-Composer#8519]
## Describe the bug

When using Composer 2.1 behind a proxy the sign in step during publishing fails. Reports error "Azure sign-in
Sign in failed: No Azure Directories were found.".

I have HTTP_PROXY and HTTPS_PROXY set.

My Azure account is a personal account.

Publishing worked using Composer 1.4.1

## Browser

- [ X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

Just following the usual publish process.

## Expected behavior

Can publish the bot like it worked in Composer 1.4.1

**Comment by JohnRobertGreen** [comment]
Having changed to Composer 2.0 I can report that the Azure login during the publish process works, but I then encounter the error reported in #8509.

**Comment by srinaath** [comment]
@JohnRobertGreen Closing this ticket as the proxy issue is resolved in 2.0

**Comment by JohnRobertGreen** [comment]
I'm using Composer 2.1 - so its not solved. Perhaps you can explain what configuration is necessary to make it work?

**Comment by JohnRobertGreen** [comment]
Just to reiterate my point - The Azure sign-on works in Composer 2.0 and does not work in Composer 2.1; this call should not be closed.
