### ISSUE TITLE
Logging into Microsoft Account in Composer 2.1.2 fails due to Tenant not being found

### ISSUE THREAD

**Issue by chookhen60** [microsoft/BotFramework-Composer#8974]
## Describe the bug

In Bot Composer 2.1.2, when I attempt to login to my Azure account within composer (or if I do this at bot publish time)I am no longer prompted to choose which directory (tenant) to choose from, and instead the process throws an error telling me it cannot find the Tenant it is looking for.  In my particular case, the TenantID does exist in Azure, and it actually the one I was using to publish to in Composer 2.1.1.

NOTE: Our company's Azure environment has a number of Tenants set up, however we only ever publish the bot to the same Tenant.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer 2.1.2
2. In the top right corner, attempt to login, or if already logged in from Composer 2.1.1 (login looks to persist between version) attempt to switch directory
3. When the login prompt appears, enter your email address corresponding to the Azure account
4. It will then ask (for me) to approve the login via the authenticator app (NOTE: In 2.1.1, it was asking for my password before this step, so this is also a change and may be the reason for this all going bad)
5. Once the approval has been given on the Authenticator app, an error is immediately thrown saying the Tenant cannot be found

## Expected behavior
1. I would have expected the login process to ask for my password prior to the authenticator app step
2. Once the Authenticator app approval was completed, I would have expected to be presented with the 'choose a Tenant' dialog where I can select the tenant I wish to use

## Screenshots
This is the resultant error I receive after approving the login via the authenticator app on my phone:
![image](https://user-images.githubusercontent.com/27396264/152877439-9504a507-a1b0-44a4-8263-6ac299c65f2d.png)

## Additional context

Attempting to perform the login at publish time, rather than from the top-right of Composer makes no difference and the same problem is observed.

**Comment by ramfattah** [comment]
Hi there, could you please try to clear the composer data/cache?

1) Open composer and click "View"
     <img src="https://i.gyazo.com/3d04a8b5b8ba0f692a03b24c13422da5.png" width="350"/>
2) click "Toggle Developer Tools"
3) In the "Developer Tools", click "Application" tab, open "Clear storage" on left nav menu and click "Clear site data".
     <img src="https://i.gyazo.com/daff5383cf4395c33d74f2786309d026.png" width="500"/>

try the above steps and let me if you are able to log in.

**Comment by ramfattah** [comment]
I found this similar issue https://github.com/microsoft/BotFramework-Composer/issues/8834 that was resolved by clearing out the system keychain of azure-related keys on a Mac. Perhaps clearing the windows credentials might help? 

Clear Windows Credentials using "Credential Manager":
1) On your Windows OS, click start
2) Search for "Credential Manager"
     <img src="https://i.gyazo.com/da014923e5c5f7395d89e2de8016e788.png" width="500"/>
3) Click "Windows Credentials"
     <img src="https://i.gyazo.com/d4c15404ee004cb00de47d6ad3652300.png" width="700"/>
4) Clear azure related credentials

Try these steps and let me know if this works.

**Comment by chookhen60** [comment]
@ramfattah I followed the process you documented above and cleared anything that could relate to Azure, including credentials to Azure devOps just to make sure.  Sadly, it did not resolve the issue.

I tried to re-produce the issue on a non-development machine I have here, and I can confirm the issues does NOT occur on that machine (I tried a few different things, but the login always worked on 2.1.2), only on my main development machine.  I do suspect it is some sort of caching issue, but I have no idea where it is pulling this info from - I also cleared the last 4 weeks of browser data, and logged out of any Azure logins in my Chrome browser to try and cover all the bases (in case anything is getting shared), but this also did not help.

**Comment by ramfattah** [comment]
Thank you for trying to repro on a different machine, closing due to confirmation.

**Comment by chookhen60** [comment]
@ramfattah I still feel like there is a bug here - it DOES work on the affected machine in 2.1.1 with no issues, and does NOT work in 2.1.2.  So clearly there has been some change to cause the issue that needs to be addressed?

**Comment by pekanovics** [comment]
@ramfattah If something only works on specific machines, that software is not considered working! Solve the underlying issue, or at least provide an explanation of why it's happening!

**Comment by ramfattah** [comment]
Hi @pekanovics, Thanks for engaging in the Microsoft Bot Composer project. I'm re-opening this issue and will check internally what might be causing this unable to login due to the Tenant not found.

**Comment by ramfattah** [comment]
@chookhen60  @pekanovics. I will report back once I find more information.

**Comment by ramfattah** [comment]
hi @chookhen60, 

can you check if you're in the correct azure directory using the Azure cli. [Commands in an Azure subscription](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli#:~:text=the%20Azure%20CLI.-,Commands%20in%20an%20Azure%20subscription,-Many%20Azure%20CLI)

In Powershell, enter the following command: `az account list --output table`

**Comment by ramfattah** [comment]
hi @chookhen60, 

Could you please check if you're in the correct azure directory using the Azure cli. [Commands in an Azure subscription](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli#:~:text=the%20Azure%20CLI.-,Commands%20in%20an%20Azure%20subscription,-Many%20Azure%20CLI)

In Powershell, enter the following command: `az account list --output table`

**Comment by chookhen60** [comment]
Hi @ramfattah, running the aforementioned command shows me the two subscriptions we have available, with the correct one set to `true` in the `IsDefault` column

**Comment by ramfattah** [comment]
Hi @chookhen60

Could you please try to uninstall composer and delete the following directories:

1. Uninstall Composer
     * If installed on local user, delete: `C:\Users\<USER>\AppData\Local\Programs\Bot Framework Composer`
     * If installed for all users, delete: `C:\program files\bot framework composer`
     * Delete `C:\Users\<USER>\AppData\Roaming\BotFrameworkComposer`
2. Download & install the latest version of Composer [here ](https://github.com/microsoft/BotFramework-Composer/releases) and try to sign in.

Try the above steps and let me know if this works.

**Comment by ramfattah** [comment]
Hi @pekanovics, thanks for following up.

Interesting, I'm not sure if it is caused by this same issue. Let's try the above [solution ](https://github.com/microsoft/BotFramework-Composer/issues/8974#issuecomment-1054708759) and try to sign in again.
Let me know if this worked.

**Comment by chookhen60** [comment]
Hi @ramfattah Apologies for the delayed response.  We are doing development work on our bot right now and getting a gap to test this can be tricky.

I followed your instructions above (note I have it installed for 'all users') and when attempting to sign in after starting a freshly installed 2.1.2 version, I got exactly the same error as @pekanovics.  This is the first time I have seen this error too, so it seems something may have changed at the login end around how this is being handled?

**Comment by ramfattah** [comment]
Hi @chookhen60, we are investigating this issue. Thanks.

**Comment by chookhen60** [comment]
@ramfattah Thanks for the update and investigation undertaken - I can confirm there are no issues around sign in with composer 2.1.1 and am using that currently to continue development on our bot.

Please keep us up to date once these issues have been resolved and we can begin using composer 2.1.2+

**Comment by ramfattah** [comment]
thank you @chookhen60 for your patience! sounds good.

**Comment by ramfattah** [comment]
I am closing this one for now, please feel free to re-open it if you are still having login issues in 2.1.1

**Comment by crismogram** [comment]
Confirming that 2.1.1 works and having the same issue with 2.1.2
