### ISSUE TITLE
is:issue is:open Won't let me installMicrosoft Bot Componet Recognizers.CLU Recognizer

### ISSUE THREAD

**Issue by Butcheva** [microsoft/BotFramework-Composer#9699]

**Comment by OEvgeny** [comment]
@Butcheva what's the error message shown? Could you provide reproduction steps?

**Comment by sijonjas** [comment]
I am also have issue with installing the package

**Comment by sijonjas** [comment]
Hi @sijonjas, I have a same issue not let me install the CLU, tried different version of the CLU. This is an error that  I get : 

If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
**A problem occured during the install of this Component: Error certificate has expired *** Could not merge components *****
Thank you for your help. I need a fix for this as I am working on my project and deadline is close. Thank you

**Comment by OEvgeny** [comment]
@sijonjas, @Butcheva please use the nightly release instead of stable. Certificate issue is fixed there

**Comment by midhunkalathilapipeople** [comment]
@OEvgeny  , I tried the same, Still getting same error!!!
 
A problem occured during the install of this Component: Error certificate has expired *** Could not merge components ***

**Comment by midhunkalathilapipeople** [comment]
Hi @OEvgeny ,

Thank you for the quick replay ,

I tried with nightly version (2.1.3) as well but , With that the package explored didn't list the package "Microsoft.Bot.Components.Recognizers.CLURecognizer".

I am creating a empty bot using .NET.

One thing i notice that i am getting the same error even i open the package manager 

![image](https://github.com/microsoft/BotFramework-Composer/assets/120084287/35e0eeb3-f3c9-4c3c-a7c1-de6ed531d45c)
